-- ==============================================================================
-- Brain Shell Keybinds
-- Auto-generated by Quickshell. Do not edit manually.
-- ==============================================================================

local shell = "/home/henrygoncalvess/.config/Brain_Shell"

-- ==============================================================================
-- BrainShell Capture Submap (Disables all normal binds during recording)
-- ==============================================================================
hl.define_submap("BrainShell_clean", function()
    -- Emergency exit in case the shell crashes during capture
    hl.bind("CTRL + ESCAPE", function()
        hl.dispatch(hl.dsp.exec_cmd("notify-send 'BrainShell' 'Emergency Exit: Keybinds re-enabled.'"))
        hl.dispatch(hl.dsp.submap("reset"))
    end, { description = "Emergency return to global submap" })
end)

-- ==============================================================================
-- User Defined Bindings
-- ==============================================================================
