services:
  frigate:
    container_name: frigate
    privileged: true # Required to access hardware acceleration and video cache
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1gb" # Crucial for handling 1080p frame buffer allocations without crashes

    # Uncomment the two lines below if you are using an Intel Mini PC (i3/i5/etc).
    # This enables Intel QuickSync (hardware video decoding) and reduces CPU load close to 0%.
    # devices:
    #   - /dev/dri/renderD128

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      # Tmpfs maps the temporary video cache directly into your RAM.
      # This protects your SSD/HDD from destructive 24/7 continuous write cycles.
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000 # ~1GB allocation in RAM
    ports:
      - "8554:8554" # Internal RTSP rebroadcast server
      - "8555:8555/tcp" # WebRTC
      - "8555:8555/udp" # WebRTC

  proxy:
    image: caddy:alpine
    container_name: proxy-auth
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frigate
